spring:
  application:
    name: SimpleNotes
  config:
    import: optional:application-secrets.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/simple_notes_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: strict
  error:
    whitelabel:
      enabled: false
    include-message: never
    include-stacktrace: never

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET}
